### PR TITLE
Added a C program of array traversal.

### PR DESCRIPTION
**Pull request by Shikha785**
Please review my code and merge it under hactoberfest accepted.

### CODE REVIEW

**Comment by Shikha785** [comment]
Thank you for merging @Sirajmolla

**Comment by Shikha785** [comment]
Hey,
 My pr is accepted under hactoberfest and now it excluded from
hactoberfest.Please help me regarding this issue.

Thank you

**Comment by Sirajmolla** [comment]
https://github.com/coder2hacker/Explore-open-source.git

Use above repo I will accet pr

**Comment by Shikha785** [comment]
Should I made pr with same code or some different code ?

**Pull request merged**
